workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      ios:
        version: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
