workflows:
  version: 2.0
  android_build:
    name: Build Android APK
    instance_type: mac_mini
    max_build_duration: 60
    timeout: 30
    steps:
      - checkout
      - flutter-install
      - flutter-build:
          platform: android
      - upload-artifact:
          artifact_path: build/app/outputs/flutter-apk/app-release.apk
          target: /tmp/artifacts/
