name: Build iOS Application

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build iOS Release IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Install dependencies
        run: flutter pub get

